# Generated by Django 2.2.7 on 2019-11-08 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='greenhouse',
            fields=[
                ('id_green', models.IntegerField(primary_key=True, serialize=False)),
                ('temp_max', models.FloatField()),
                ('temp_min', models.FloatField()),
                ('hum_max', models.FloatField()),
                ('hum_min', models.FloatField()),
                ('fk_id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greenBoy.User')),
            ],
        ),
        migrations.CreateModel(
            name='graphs',
            fields=[
                ('id_graph', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.TimeField(auto_now_add=True)),
                ('temp', models.FloatField()),
                ('hum', models.FloatField()),
                ('fk_id_green', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greenBoy.greenhouse')),
            ],
        ),
    ]
