# Generated by Django 2.2.7 on 2019-11-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenBoy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphs',
            name='id_graph',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='greenhouse',
            name='id_green',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_user',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
