# Generated by Django 2.2.7 on 2019-11-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenBoy', '0003_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenhouse',
            name='greenName',
            field=models.CharField(default='', max_length=40),
        ),
    ]
