# Generated by Django 2.2.7 on 2019-11-22 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greenBoy', '0008_auto_20191121_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphs',
            name='fk_id_green',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greenBoy.Greenhouse'),
        ),
    ]
