# Generated by Django 2.2.7 on 2019-11-22 05:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('greenBoy', '0012_auto_20191121_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphs',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='graphs',
            name='fk_id_green',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greenBoy.Greenhouse'),
        ),
    ]
